version: "3.8"

services:
  api01: &api
    image: miguelarquejada/rinha-de-backend:latest
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
    deploy:
      resources:
        limits:
          # 1.5 unidades de CPU e 550MB
          cpus: "0.13"
          memory: "140MB"

volumes:
  postgres_data:


networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1